# Latest documentation available at https://omines.github.io/datatables-bundle/#configuration
datatables:
    language_from_cdn: false
    options:
        lengthMenu : [5, 10, 15, 30]
        pageLength: 5
        dom: "<'row' <'col-sm-12' ftr>><'row' <'col-sm-6'l> <'col-sm-6 text-right'pi>>"
        searching: true

    template:             '@DataTables/datatable_html.html.twig'
    template_parameters:
        # Example classes to integrate nicely with Bootstrap 3.x
        className: 'table table-striped table-bordered table-hover data-table'
        columnFilter: 'thead'
    # You can for example override this to "tables" to keep the translation domains separated nicely
    translation_domain: 'messages'
